### PR TITLE
Ensure compatibility with promise-spec

### LINKED ISSUE #483: Using render().promise() with bluebird
If I send the promise from `view.render().promise()` into `BluebirdPromise.resolve()` it crashes Chrome. Any idea why?

See jsbin: https://jsbin.com/xaxeta/6/edit?js,console,output

Just remove the comments in `Promise.resolve`, and it'll crash

Using `jQuery.Deferred()` and `jQuery.Deferred().promise()` (which I think is what happens under the hood) directly works fine with bluebird

### PR DESCRIPTION
**Pull request by SimenB**
Fix #483

While it's a nice shorthand, the promise crashes Chrome if passed into bluebird. The problem is that the view is a `thenable` recursively resolving to itself which is a `thenable` and then you're stuck in an endless loop. 
It's a breaking change, though...

EDIT: Tests fail because `Promise` does not exist in node 0.10. How do I `require` if running in node for the tests?

EDIT2: Tests pass now, but it's a bit ugly on the new test. Suggestions?

### CODE REVIEW

File: backbone.layoutmanager.js [hunk 1]
```diff
@@ -86,9 +86,9 @@ var LayoutManager = Backbone.View.extend({
     if (beforeRender) {
       var ret = beforeRender.call(view, view);
 
-      if (ret && ret.then) {
+      if (ret && ret.promise) {
```
Comment (SimenB) [inline backbone.layoutmanager.js]: This specific change might not be good looking at it again.  Before render returns a promise and not a view, right?

File: backbone.layoutmanager.js [hunk 2]
```diff
@@ -297,7 +292,7 @@ var LayoutManager = Backbone.View.extend({
 
     // Once all child views have completed rendering, resolve parent deferred
     // with the correct context.
-    root.when(promises).then(function() {
+    root.when(promises).promise().then(function() {
```
Comment (SimenB) [inline backbone.layoutmanager.js]: This too might be bad

**Comment by SimenB** [comment]
@tbranyen thoughts?

File: .gitignore [hunk 3]
```diff
@@ -2,3 +2,4 @@ node_modules
 test/report
 test/tmp
 bower_components
+.idea/
```
Comment (tbranyen) [inline .gitignore]: What is this for?

File: backbone.layoutmanager.js [hunk 4]
```diff
@@ -262,11 +262,6 @@ var LayoutManager = Backbone.View.extend({
     return this.__manager__.renderDeferred.promise();
   },
 
-  // Proxy `then` for easier invocation.
-  then: function() {
-    return this.promise().then.apply(this, arguments);
```
Comment (tbranyen) [inline backbone.layoutmanager.js]: Do we know *why* this breaks?

File: .gitignore (hunk 3 above)
Comment (SimenB) [inline .gitignore]: IntelliJ project files. I can remove the change

Comment (tbranyen) [inline .gitignore]: Okay cool, thanks! This would be best in your global Git config.

File: backbone.layoutmanager.js (hunk 4 above)
Comment (tbranyen) [inline backbone.layoutmanager.js]: I'm still looking into the issue.  It seems to be because of the property named `then`, but we're only passing the `promise()` return value into Bluebird resolve, so why should that matter.

File: .gitignore (hunk 3 above)
Comment (SimenB) [inline .gitignore]: There are certain projects I like to keep them in, but I have no problem with removing the change :smile:

File: backbone.layoutmanager.js (hunk 4 above)
Comment (SimenB) [inline backbone.layoutmanager.js]: Some discussion here: petkaantonov/bluebird#728

File: .gitignore (hunk 3 above)
Comment (SimenB) [inline .gitignore]: Removed

File: backbone.layoutmanager.js (hunk 4 above)
Comment (tbranyen) [inline backbone.layoutmanager.js]: Ah, in that case wouldn't it better to just change our Promise resolution to not resolve to the View?

Comment (SimenB) [inline backbone.layoutmanager.js]: How to do that though? I tried doing 
```js
then: function() {		
  return this.promise().then.apply(null, arguments);
}
```
Didn't work

Did not try

```js
then: function() {		
  return this.promise().then();
}
```
though, not sure if it matters

Comment (tbranyen) [inline backbone.layoutmanager.js]: I think the problem is with `resolveWith` since we are setting the resolved value to be the View. I don't think there's anything wrong with our thennable method, just our Promise resolution.

Comment (SimenB) [inline backbone.layoutmanager.js]: Ah. Setting `this` in the promise is quite handy though, more useful imo than avoiding a single method-call (`.promise()`).

Comment (SimenB) [inline backbone.layoutmanager.js]: `.resolveWith(null, [this])`, maybe?

Comment (tbranyen) [inline backbone.layoutmanager.js]: Yeah, I suppose you lose that, but you gain less overall changes.  Either way we'll need a minor bump.

Comment (SimenB) [inline backbone.layoutmanager.js]: FWIW, personally I already use `.promise`, as that was what was stated in the upgrade guide. Didn't even know I could do `.then` on the view until this issue popped up.
On the other hand, I DO utilize the fact that `this` refers to the view`. I'll gladly refactor to using the argument, as I'm no real fan of magical `this`. :laughing:

Want me to make a PR for `reoslveWith` (if I can make it wor)?

Comment (tbranyen) [inline backbone.layoutmanager.js]: Actually, no.  You make a really good point.  I only added `then` to support legacy. Maybe we should just dump that weird baggage now.

Comment (SimenB) [inline backbone.layoutmanager.js]: I'm all for it! I think just dumping `then` is a fair compromise between spec compliance and usability. Our `this`es are broken these days anyway because of arrow functions.
Your call!

**Comment by tbranyen** [comment]
Looks good. Thanks for taking the time to work with me on this @SimenB!

**Comment by SimenB** [comment]
Great, thanks! Any plans for a release soon-ish? Currently tightening up the async parts of our app, this'd make it prettier in places :smile:

**Comment by SimenB** [comment]
@tbranyen, hey, any chance of this making it into a release soon :smile:

**Comment by SimenB** [comment]
@tbranyen Any chance of a release :smile:

**Comment by tbranyen** [comment]
lol so sorry @SimenB, I'll do it today!

**Comment by tbranyen** [comment]
@SimenB all set, 0.10.0!

**Comment by SimenB** [comment]
Sweet, thanks!
